import Head from 'next/head';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon" href="/chatbot.ico" />
        <meta name="description" content="Generated by Next.js" />
        <title>Buddy</title>
      </Head>
      <body>{children}</body>
    </html>
  )
}
