import Head from 'next/head';

export const metadata = {
  title: 'Buddy',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="/chatbot.png" />
        <meta name="description" content="Generated by Next.js" />
        <title>Buddy</title>
      </Head>
      <body>{children}</body>
    </html>
  )
}
